DROP DATABASE IF EXISTS JUEGO;
CREATE DATABASE JUEGO;

USE JUEGO;

CREATE TABLE JUGADORES(
	ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOMBRE TEXT NOT NULL,
	USUARIO TEXT NOT NULL,
	PASSWORD TEXT NOT NULL,
	EDAD INTEGER NOT NULL,
	PUNTUACION INTEGER,
	VICTORIAS INTEGER
)ENGINE = InnoDB;

CREATE TABLE PARTIDA(
	ID INTEGER PRIMARY KEY NOT NULL,
	DURACION INTEGER NOT NULL,
	GANADOR INTEGER NOT NULL,
	FECHA DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB;

CREATE TABLE ENFRENTAMIENTOS(
	ID_J1 INTEGER NOT NULL,
	ID_J2 INTEGER NOT NULL,
	ID_P INTEGER PRIMARY KEY NOT NULL,
	PUNTUACION INTEGER,
	FOREIGN KEY(ID_J1) REFERENCES JUGADORES(ID),
	FOREIGN KEY(ID_J2) REFERENCES JUGADORES(ID),
	FOREIGN KEY(ID_P) REFERENCES PARTIDA(ID)
)ENGINE = InnoDB;

INSERT INTO JUGADORES(NOMBRE, USUARIO, PASSWORD, EDAD, PUNTUACION, VICTORIAS) VALUES('JAN','JANNOG','123', 21, 5630, 10);
INSERT INTO JUGADORES(NOMBRE, USUARIO, PASSWORD, EDAD, PUNTUACION, VICTORIAS) VALUES('GERARD','ALV45','123', 20, 2960, 6);
INSERT INTO JUGADORES(NOMBRE, USUARIO, PASSWORD, EDAD, PUNTUACION, VICTORIAS) VALUES('ERIC','ERLEON','123', 20, 495, 2);

INSERT INTO PARTIDA(ID, DURACION, GANADOR) VALUES(1,124,1);
INSERT INTO PARTIDA(ID, DURACION, GANADOR) VALUES(2,150,2);
INSERT INTO PARTIDA(ID, DURACION, GANADOR) VALUES(3,40,1);
INSERT INTO PARTIDA(ID, DURACION, GANADOR) VALUES(4,66,3);
INSERT INTO PARTIDA(ID, DURACION, GANADOR) VALUES(5,98,1);

INSERT INTO ENFRENTAMIENTOS(ID_J1, ID_J2, ID_P, PUNTUACION) VALUES(1,2,1,2394);
INSERT INTO ENFRENTAMIENTOS(ID_J1, ID_J2, ID_P, PUNTUACION) VALUES(2,3,2,3234);
INSERT INTO ENFRENTAMIENTOS(ID_J1, ID_J2, ID_P, PUNTUACION) VALUES(1,3,3,5634);
INSERT INTO ENFRENTAMIENTOS(ID_J1, ID_J2, ID_P, PUNTUACION) VALUES(2,3,4,1234);
INSERT INTO ENFRENTAMIENTOS(ID_J1, ID_J2, ID_P, PUNTUACION) VALUES(1,2,5,2343);