DROP DATABASE IF EXISTS JUEGO;
CREATE DATABASE JUEGO;

USE JUEGO;

CREATE TABLE JUGADORES(
	ID INTEGER PRIMARY KEY NOT NULL,
	NOMBRE TEXT NOT NULL,
	USUARIO TEXT NOT NULL,
	PASSWORD TEXT NOT NULL,
	EDAD INTEGER NOT NULL,
	PUNTUACION INTEGER,
	VICTORIAS INTEGER
)ENGINE = InnoDB;

CREATE TABLE PARTIDAS(
	ID INTEGER PRIMARY KEY NOT NULL,
	DURACION INTEGER NOT NULL,
	GANADOR INTEGER NOT NULL,
	FECHA DATETIME
)ENGINE = InnoDB;

CREATE TABLE ENFRENTAMIENTOS(
	ID_1 INTEGER NOT NULL,
	ID_2 INTEGER NOT NULL,
	PARTIDA INTEGER NOT NULL,
	PUNTUACION INTEGER
)ENGINE = InnoDB;

INSERT INTO JUGADORES(ID, NOMBRE, USUARIO, PASSWORD, EDAD, PUNTUACION, VICTORIAS) VALUES(1,'JAN','JANNOG','CONTRASEÑA123', 21, 5630, 10);
INSERT INTO JUGADORES(ID, NOMBRE, USUARIO, PASSWORD, EDAD, PUNTUACION, VICTORIAS) VALUES(2,'GERARD','ALV45','PAPASITORICO', 20, 2960, 6);
INSERT INTO JUGADORES(ID, NOMBRE, USUARIO, PASSWORD, EDAD, PUNTUACION, VICTORIAS) VALUES(3,'ERIC','ERLEON','SALCHIPAPA', 20, 495, 2);

INSERT INTO PARTIDAS(ID, DURACION, GANADOR) VALUES(1,124, 1);
INSERT INTO PARTIDAS(ID, DURACION, GANADOR) VALUES(2,150, 2);
INSERT INTO PARTIDAS(ID, DURACION, GANADOR) VALUES(3,40, 1);
INSERT INTO PARTIDAS(ID, DURACION, GANADOR) VALUES(4,66, 3);
INSERT INTO PARTIDAS(ID, DURACION, GANADOR) VALUES(5,98, 1);

INSERT INTO ENFRENTAMIENTOS(ID_1, ID_2, PARTIDA, PUNTUACION) VALUES(1,2,1,2394);
INSERT INTO ENFRENTAMIENTOS(ID_1, ID_2, PARTIDA, PUNTUACION) VALUES(2,3,2,3234);
INSERT INTO ENFRENTAMIENTOS(ID_1, ID_2, PARTIDA, PUNTUACION) VALUES(1,3,3,5634);
INSERT INTO ENFRENTAMIENTOS(ID_1, ID_2, PARTIDA, PUNTUACION) VALUES(2,3,4,1234);
INSERT INTO ENFRENTAMIENTOS(ID_1, ID_2, PARTIDA, PUNTUACION) VALUES(1,2,5,2343);
